import os

print("[+] Installing requierments ...")
os.system('pip install termcolor')
os.system('pip install colorama')
os.system('pip install requests')
os.system('pip install rich')
os.system('pip install tgcrypto')
os.system('pip install IP2Location')
os.system('pip install pytz')
os.system('pip install licensing')
os.system('pip install pyfiglet')
os.system('pip uninstall -y setuptools')
os.system('pip install setuptools==66.0.0')
os.system('pip install pick')
os.system('pip install asyncio')
os.system('pip install configparser')
os.system('pip install lolpython')
os.system('pip install pyrogram')
os.system('pip install telethon')
os.system('pip install vobject')
os.system('pip install geopy')
os.system('pip install names')
os.system('pip install Faker')
os.system('pip install Faker')
os.system('pip install gender-guesser')

print("[+] setup complete !")
print("[+] now you can run any tool !")